spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          addLabelLocations: false
          search-locations:
          - classpath:config/core/{application}/{profile}
          - classpath:config/infra/{application}
          - classpath:config/stats/{application}/{profile}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
server:
  port: ${SERVER_PORT:9091}