spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    discovery:
      enabled: true
    config:
      server:
        native:
          addLabelLocations: false
          search-locations:
          - classpath:config/core/{application}/{profile}
          - classpath:config/infra/{application}
          - classpath:config/stats/{application}/{profile}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10
server:
  port: ${SERVER_PORT:0}