collector:
  kafka:
    topics:
      userActions: "stats.user-actions.v1"
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: ${collector.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.AvroSerializer