DROP TABLE IF EXISTS event_ratings CASCADE;

CREATE TABLE IF NOT EXISTS event_ratings
(
    rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    event_id  BIGINT                                  NOT NULL,
    is_like   BOOLEAN                                 NOT NULL,
    CONSTRAINT unique_user_likes_event UNIQUE (user_id, event_id)
);
