spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: ewm_main_service_route
          uri: lb://ewm-main-service

          predicates:
            - Path=/**


#        - id: ewm_stats_server_route
#          uri: lb://ewm-stats-server
#
#          predicates:
#            - Path=/ewm-stats-server/**

server:
  port: 8080