spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: ewm_user_service_route_users
          uri: lb://ewm-user-service
          predicates:
            - Path=/users/**
        - id: ewm_user_service_route_admin_users
          uri: lb://ewm-user-service
          predicates:
            - Path=/admin/users/**
        - id: ewm_event_service_route
          uri: lb://ewm-event-service
          predicates:
            - Path=/events/**
        - id: ewm_event_service_route_admin_event
          uri: lb://ewm-event-service
          predicates:
            - Path=/admin/events/**


        - id: ewm_request_service_route
          uri: lb://ewm-request-service

          predicates:
            - Path=/requests/**


#        - id: ewm_stats_server_route
#          uri: lb://ewm-stats-server
#
#          predicates:
#            - Path=/ewm-stats-server/**

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG