spring:
  application:
    name: ewm-main-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8081